In [2]:
import pandas as pd 
import numpy as np

In [3]:
matches = pd.read_excel(r'C:\Users\OrdiOne\OneDrive\Bureau\Python data analysis projects\espncricinfo.xlsx')
matches

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
60,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
61,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11
62,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
63,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [4]:
#relabel columns
matches = matches.rename(columns={"Mat":"Matches_Played", "Inns":"innings_batted", "NO":"not_outs", "Runs":"runs_scored", "HS":"highest_inns_score", "Ave":"batting_average", "BF":"balls_faced","SR":"batting_strike_rate","100":"100_scored","50":"50_scored","0":"ducks_scored","4s":"boundary_fours","6s":"boundary_sixes"})

In [5]:
matches

,Player,Span,Matches_Played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100_scored,50_scored,ducks_scored,boundary_fours,boundary_sixes
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
60,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
61,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11
62,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
63,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [6]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Player               64 non-null     object
 1   Span                 64 non-null     object
 2   Matches_Played       64 non-null     int64
 3   innings_batted       64 non-null     int64
 4   not_outs             64 non-null     int64
 5   runs_scored          64 non-null     int64
 6   highest_inns_score   64 non-null     object
 7   batting_average      64 non-null     float64
 8   balls_faced          61 non-null     object
 9   batting_strike_rate  61 non-null     float64
 10  100_scored           64 non-null     int64
 11  50_scored            64 non-null     int64
 12  ducks_scored         64 non-null     int64
 13  boundary_fours       64 non-null     int64
 14  boundary_sixes       64 non-null     int64
dtypes: float64(2), int64(9), object(4)
memory usage: 7.6+ KB

In [7]:
matches.isnull().any()

Player                 False
Span                   False
Matches_Played         False
innings_batted         False
not_outs               False
runs_scored            False
highest_inns_score     False
batting_average        False
balls_faced             True
batting_strike_rate     True
100_scored             False
50_scored              False
ducks_scored           False
boundary_fours         False
boundary_sixes         False
dtype: bool

In [8]:
matches["balls_faced"].unique()

array(['9800+', 1287, 2667, '1707+', '416+', '6558+', '1288+', '4957+',
       nan, 17292, '7491+', '4063+', 22882, 2395, '5363+', '2844+', 28903,
       '178+', 15785, '665+', 1823, '13079+', '108+', '29437+', 7146,
       19753, '15164+', 31258, 14372, 19375, 22782, '2035+', 10636, 12436,
       27395, '14184+', 22461, 2764, 14349, 16077, '27002+', 20113,
       '9613+', 2719, '2731+', 22959, 16345, '488+', '619+', 2445, 15456,
       '885+', '158+', 11641, '1799+', '8662+', '3217+', '2110+'],
      dtype=object)

In [9]:
matches[matches["balls_faced"].isna()==1]

,Player,Span,Matches_Played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100_scored,50_scored,ducks_scored,boundary_fours,boundary_sixes
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258,2
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107,11
56,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,NaN,NaN,5,6,3,51,0

In [10]:
matches["balls_faced"] = matches["balls_faced"].fillna(0)

In [11]:
matches["balls_faced"].unique()

array(['9800+', 1287, 2667, '1707+', '416+', '6558+', '1288+', '4957+', 0,
       17292, '7491+', '4063+', 22882, 2395, '5363+', '2844+', 28903,
       '178+', 15785, '665+', 1823, '13079+', '108+', '29437+', 7146,
       19753, '15164+', 31258, 14372, 19375, 22782, '2035+', 10636, 12436,
       27395, '14184+', 22461, 2764, 14349, 16077, '27002+', 20113,
       '9613+', 2719, '2731+', 22959, 16345, '488+', '619+', 2445, 15456,
       '885+', '158+', 11641, '1799+', '8662+', '3217+', '2110+'],
      dtype=object)

In [12]:
def convert_balls_faced(balls_faced):
    if isinstance(balls_faced, str):
        return balls_faced.strip('+')
    else:
        return balls_faced
    
matches["balls_faced"] = matches["balls_faced"].apply(convert_balls_faced)

In [13]:
# Convert 'balls_faced' column from object to int
matches['balls_faced'] = matches['balls_faced'].astype(int)

In [14]:
matches["balls_faced"].unique()

array([ 9800,  1287,  2667,  1707,   416,  6558,  1288,  4957,     0,
       17292,  7491,  4063, 22882,  2395,  5363,  2844, 28903,   178,
       15785,   665,  1823, 13079,   108, 29437,  7146, 19753, 15164,
       31258, 14372, 19375, 22782,  2035, 10636, 12436, 27395, 14184,
       22461,  2764, 14349, 16077, 27002, 20113,  9613,  2719,  2731,
       22959, 16345,   488,   619,  2445, 15456,   885,   158, 11641,
        1799,  8662,  3217,  2110])

In [15]:
matches["batting_strike_rate"] = matches["batting_strike_rate"].fillna(0)

In [16]:
matches["batting_strike_rate"].unique()

array([58.6 , 91.76, 55.68, 54.48, 56.  , 34.59, 45.88, 42.42,  0.  ,
       53.89, 38.07, 53.58, 54.19, 54.94, 46.22, 39.34, 45.97, 29.21,
       51.46, 35.48, 59.46, 51.53, 63.88, 54.04, 53.02, 60.51, 45.99,
       42.51, 52.39, 52.12, 58.72, 44.86, 45.07, 50.13, 43.31, 43.35,
       48.64, 44.13, 60.1 , 54.51, 41.09, 56.75, 69.77, 51.59, 38.81,
       51.45, 54.02, 40.16, 30.04, 48.26, 55.92, 37.74, 29.11, 46.92,
       43.74, 49.16, 60.02, 25.59])

In [17]:
matches.isnull().any()

Player                 False
Span                   False
Matches_Played         False
innings_batted         False
not_outs               False
runs_scored            False
highest_inns_score     False
batting_average        False
balls_faced            False
batting_strike_rate    False
100_scored             False
50_scored              False
ducks_scored           False
boundary_fours         False
boundary_sixes         False
dtype: bool

In [18]:
#drop duplicates 
matches.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
59    False
60     True
61     True
62    False
63    False
Length: 64, dtype: bool

In [19]:
matches[matches["Player"].duplicated()==1]

,Player,Span,Matches_Played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100_scored,50_scored,ducks_scored,boundary_fours,boundary_sixes
50,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
51,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11
60,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
61,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11

In [20]:
matches= matches.drop_duplicates()
matches[matches["Player"].duplicated()==1]

Empty DataFrame
Columns: [Player, Span, Matches_Played, innings_batted, not_outs, runs_scored, highest_inns_score, batting_average, balls_faced, batting_strike_rate, 100_scored, 50_scored, ducks_scored, boundary_fours, boundary_sixes]
Index: []

In [21]:
matches

,Player,Span,Matches_Played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100_scored,50_scored,ducks_scored,boundary_fours,boundary_sixes
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416,56.00,10,5,2,104,1
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6
6,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4
7,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2
9,SPD Smith (AUS),2010-2023,102,181,22,9320,239,58.61,17292,53.89,32,39,9,1026,52
10,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491,38.07,22,24,4,419,27
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063,53.58,26,30,12,593,32
12,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
13,DJ Mitchell (NZ),2019-2023,18,27,4,1316,190,57.21,2395,54.94,5,8,1,130,26
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11
16,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
18,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2
19,KS Williamson (NZ),2010-2023,94,164,16,8124,251,54.89,15785,51.46,28,33,10,897,21
20,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1
21,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
22,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079,51.53,24,31,12,755,16
23,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6
24,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437,54.04,51,68,14,2058,69
25,M Labuschagne (AUS),2018-2023,43,76,5,3789,215,53.36,7146,53.02,11,16,4,427,12
26,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
27,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164,45.99,23,43,6,788,48
28,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
29,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
30,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
31,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
32,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035,44.86,3,9,1,102,3
33,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
34,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
35,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
36,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184,43.35,34,45,12,908,26
37,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
38,Abdullah Shafique (PAK),2021-2023,14,26,2,1220,201,50.83,2764,44.13,4,4,2,119,18
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
41,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28
42,JE Root (ENG),2012-2023,135,247,20,11416,254,50.29,20113,56.75,30,60,12,1247,43
43,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84
44,DP Conway (NZ),2021-2023,16,29,1,1403,200,50.10,2719,51.59,4,8,2,177,6
45,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3
46,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61
47,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
48,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11
49,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619,30.04,4,3,3,38,0
52,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5
53,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39
54,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885,37.74,3,9,2,123,20
55,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158,29.11,8,21,3,41,1
56,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,0,0.00,5,6,3,51,0
57,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7
58,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1
59,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23
62,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5
63,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0

In [22]:
matches["highest_inns_score"].unique()

array([334, 186, '269*', 274, '270*', 194, 243, 256, 207, 239, '336*',
       '365*', 319, 190, 211, 220, 364, 224, 122, 251, 183, 227, '247*',
       231, '248*', 215, '400*', '280*', 270, 223, 313, 257, '201*',
       '232*', 195, '203*', '236*', 200, 201, 380, '278*', 205, 254, 291,
       278, 374, 329, 261, '182*', '215*', '329*', '144*', '189*', 250,
       232, 127], dtype=object)

In [23]:
def convrt_highest_inns_score(highest_inns_score):
    if isinstance(highest_inns_score, str):
        return highest_inns_score.strip('*')
    else:
        return highest_inns_score
    
matches["highest_inns_score"] = matches ["highest_inns_score"].apply(convrt_highest_inns_score)
matches["highest_inns_score"] = matches["highest_inns_score"].astype(int)

C:\Users\OrdiOne\AppData\Local\Temp\ipykernel_3956\2201803902.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["highest_inns_score"] = matches ["highest_inns_score"].apply(convrt_highest_inns_score)
C:\Users\OrdiOne\AppData\Local\Temp\ipykernel_3956\2201803902.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["highest_inns_score"] = matches["highest_inns_score"].astype(int)

In [24]:
matches["highest_inns_score"].unique()

array([334, 186, 269, 274, 270, 194, 243, 256, 207, 239, 336, 365, 319,
       190, 211, 220, 364, 224, 122, 251, 183, 227, 247, 231, 248, 215,
       400, 280, 223, 313, 257, 201, 232, 195, 203, 236, 200, 380, 278,
       205, 254, 291, 374, 329, 261, 182, 144, 189, 250, 127])

In [25]:
matches

,Player,Span,Matches_Played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100_scored,50_scored,ducks_scored,boundary_fours,boundary_sixes
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6
6,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4
7,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2
9,SPD Smith (AUS),2010-2023,102,181,22,9320,239,58.61,17292,53.89,32,39,9,1026,52
10,WR Hammond (ENG),1927-1947,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27
11,GS Sobers (WI),1954-1974,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32
12,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
13,DJ Mitchell (NZ),2019-2023,18,27,4,1316,190,57.21,2395,54.94,5,8,1,130,26
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11
16,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
18,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2
19,KS Williamson (NZ),2010-2023,94,164,16,8124,251,54.89,15785,51.46,28,33,10,897,21
20,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1
21,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
22,GS Chappell (AUS),1970-1984,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16
23,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6
24,SR Tendulkar (IND),1989-2013,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69
25,M Labuschagne (AUS),2018-2023,43,76,5,3789,215,53.36,7146,53.02,11,16,4,427,12
26,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88
27,Javed Miandad (PAK),1976-1993,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48
28,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
29,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
30,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
31,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
32,J Ryder (AUS),1920-1929,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3
33,A Flower (ZIM),1992-2002,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20
34,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
35,S Chanderpaul (WI),1994-2015,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36
36,SM Gavaskar (IND),1971-1987,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26
37,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
38,Abdullah Shafique (PAK),2021-2023,14,26,2,1220,201,50.83,2764,44.13,4,4,2,119,18
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82
40,AB de Villiers (SA),2004-2018,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64
41,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28
42,JE Root (ENG),2012-2023,135,247,20,11416,254,50.29,20113,56.75,30,60,12,1247,43
43,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84
44,DP Conway (NZ),2021-2023,16,29,1,1403,200,50.10,2719,51.59,4,8,2,177,6
45,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3
46,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61
47,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48
48,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11
49,CP Mead (ENG),1911-1928,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0
52,Abid Ali (PAK),2019-2021,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5
53,MJ Clarke (AUS),2004-2015,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39
54,KC Bland (SA),1961-1966,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20
55,B Mitchell (SA),1929-1949,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1
56,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0
57,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7
58,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1
59,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23
62,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5
63,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0

In [26]:
#Split up Span into Start and Date

In [27]:
matches[["Rookie_Year","Final_Year"]] = matches["Span"].str.split("-",1,expand=True)

C:\Users\OrdiOne\AppData\Local\Temp\ipykernel_3956\2285106821.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches[["Rookie_Year","Final_Year"]] = matches["Span"].str.split("-",1,expand=True)
C:\Users\OrdiOne\AppData\Local\Temp\ipykernel_3956\2285106821.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches[["Rookie_Year","Final_Year"]] = matches["Span"].str.split("-",1,expand=True)

In [79]:
matches['Rookie_Year'] = matches['Rookie_Year'].astype(int)

In [80]:
matches['Final_Year'] = matches['Final_Year'].astype(int)

#matches = matches.astype({'Rookie_Year':'int','Final_Year':'int' })

In [28]:
matches = matches.drop(columns ="Span", inplace=False)

In [68]:
matches

,Player,Matches_Played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100_scored,50_scored,ducks_scored,boundary_fours,boundary_sixes,Rookie_Year,Final_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948
1,HC Brook (ENG),12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954
5,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935
6,E Paynter (ENG),20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939
7,KF Barrington (ENG),82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968
8,ED Weekes (WI),48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958
9,SPD Smith (AUS),102,181,22,9320,239,58.61,17292,53.89,32,39,9,1026,52,2010,2023
10,WR Hammond (ENG),85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947
11,GS Sobers (WI),93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1954,1974
12,KC Sangakkara (SL),134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015
13,DJ Mitchell (NZ),18,27,4,1316,190,57.21,2395,54.94,5,8,1,130,26,2019,2023
14,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930
15,CL Walcott (WI),44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960
16,L Hutton (ENG),79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955
17,JH Kallis (ICC/SA),166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
18,GE Tyldesley (ENG),14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929
19,KS Williamson (NZ),94,164,16,8124,251,54.89,15785,51.46,28,33,10,897,21,2010,2023
20,CA Davis (WI),15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973
21,VG Kambli (IND),17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
22,GS Chappell (AUS),87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984
23,AD Nourse (SA),34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951
24,SR Tendulkar (IND),200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013
25,M Labuschagne (AUS),43,76,5,3789,215,53.36,7146,53.02,11,16,4,427,12,2018,2023
26,BC Lara (ICC/WI),131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006
27,Javed Miandad (PAK),124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993
28,R Dravid (ICC/IND),164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
29,Mohammad Yousuf (PAK),90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
30,Younis Khan (PAK),118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
31,RT Ponting (AUS),168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
32,J Ryder (AUS),20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929
33,A Flower (ZIM),63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002
34,MEK Hussey (AUS),79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
35,S Chanderpaul (WI),164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015
36,SM Gavaskar (IND),125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1971,1987
37,SR Waugh (AUS),168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
38,Abdullah Shafique (PAK),14,26,2,1220,201,50.83,2764,44.13,4,4,2,119,18,2021,2023
39,ML Hayden (AUS),103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
40,AB de Villiers (SA),114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018
41,AR Border (AUS),156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994
42,JE Root (ENG),135,247,20,11416,254,50.29,20113,56.75,30,60,12,1247,43,2012,2023
43,IVA Richards (WI),121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991
44,DP Conway (NZ),16,29,1,1403,200,50.10,2719,51.59,4,8,2,177,6,2021,2023
45,DCS Compton (ENG),78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957
46,DPMD Jayawardene (SL),149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
47,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
48,FMM Worrell (WI),51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963
49,CP Mead (ENG),17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928
52,Abid Ali (PAK),16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021
53,MJ Clarke (AUS),115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015
54,KC Bland (SA),21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,1961,1966
55,B Mitchell (SA),42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949
56,Hon.FS Jackson (ENG),20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,1893,1905
57,TT Samaraweera (SL),81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
58,RN Harvey (AUS),79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963
59,KD Walters (AUS),74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981
62,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938
63,DR Jardine (ENG),22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934

In [30]:
#split up the country from the player

In [66]:
matches = matches.drop(columns = 'Coutry', inplace=False)

In [69]:
matches[['Player', 'Country']] = matches['Player'].str.split('(',2,expand=True)

In [74]:
matches["Country"] = matches["Country"].str.strip(')')

In [75]:
matches

,Player,Matches_Played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100_scored,50_scored,ducks_scored,boundary_fours,boundary_sixes,Rookie_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,1928,1948,AUS
1,HC Brook,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,ENG
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,1924,1935,ENG
6,E Paynter,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,ENG
8,ED Weekes,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,WI
9,SPD Smith,102,181,22,9320,239,58.61,17292,53.89,32,39,9,1026,52,2010,2023,AUS
10,WR Hammond,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,ENG
11,GS Sobers,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,1954,1974,WI
12,KC Sangakkara,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
13,DJ Mitchell,18,27,4,1316,190,57.21,2395,54.94,5,8,1,130,26,2019,2023,NZ
14,JB Hobbs,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,1908,1930,ENG
15,CL Walcott,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,WI
16,L Hutton,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG
17,JH Kallis,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
18,GE Tyldesley,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,1921,1929,ENG
19,KS Williamson,94,164,16,8124,251,54.89,15785,51.46,28,33,10,897,21,2010,2023,NZ
20,CA Davis,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,1968,1973,WI
21,VG Kambli,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
22,GS Chappell,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS
23,AD Nourse,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,1935,1951,SA
24,SR Tendulkar,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,IND
25,M Labuschagne,43,76,5,3789,215,53.36,7146,53.02,11,16,4,427,12,2018,2023,AUS
26,BC Lara,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
27,Javed Miandad,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,PAK
28,R Dravid,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
29,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
30,Younis Khan,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
31,RT Ponting,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
32,J Ryder,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,AUS
33,A Flower,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
34,MEK Hussey,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
35,S Chanderpaul,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
36,SM Gavaskar,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,1971,1987,IND
37,SR Waugh,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
38,Abdullah Shafique,14,26,2,1220,201,50.83,2764,44.13,4,4,2,119,18,2021,2023,PAK
39,ML Hayden,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
41,AR Border,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS
42,JE Root,135,247,20,11416,254,50.29,20113,56.75,30,60,12,1247,43,2012,2023,ENG
43,IVA Richards,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,WI
44,DP Conway,16,29,1,1403,200,50.10,2719,51.59,4,8,2,177,6,2021,2023,NZ
45,DCS Compton,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,ENG
46,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
47,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
48,FMM Worrell,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,1948,1963,WI
49,CP Mead,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,1911,1928,ENG
52,Abid Ali,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
53,MJ Clarke,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS
54,KC Bland,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,1961,1966,SA
55,B Mitchell,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,1929,1949,SA
56,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,1893,1905,ENG
57,TT Samaraweera,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
58,RN Harvey,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,AUS
59,KD Walters,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS
62,SJ McCabe,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS
63,DR Jardine,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG

In [76]:
matches['Country'].unique()

array(['AUS', 'ENG', 'SA', 'WI', 'SL', 'NZ', 'ICC/SA', 'IND', 'ICC/WI',
       'PAK', 'ICC/IND', 'ZIM', 'ICC/PAK'], dtype=object)

In [77]:
matches['Player'].unique()

array(['DG Bradman ', 'HC Brook ', 'AC Voges ', 'RG Pollock ',
       'GA Headley ', 'H Sutcliffe ', 'E Paynter ', 'KF Barrington ',
       'ED Weekes ', 'SPD Smith ', 'WR Hammond ', 'GS Sobers ',
       'KC Sangakkara ', 'DJ Mitchell ', 'JB Hobbs ', 'CL Walcott ',
       'L Hutton ', 'JH Kallis ', 'GE Tyldesley ', 'KS Williamson ',
       'CA Davis ', 'VG Kambli ', 'GS Chappell ', 'AD Nourse ',
       'SR Tendulkar ', 'M Labuschagne ', 'BC Lara ', 'Javed Miandad ',
       'R Dravid ', 'Mohammad Yousuf ', 'Younis Khan ', 'RT Ponting ',
       'J Ryder ', 'A Flower ', 'MEK Hussey ', 'S Chanderpaul ',
       'SM Gavaskar ', 'SR Waugh ', 'Abdullah Shafique ', 'ML Hayden ',
       'AB de Villiers ', 'AR Border ', 'JE Root ', 'IVA Richards ',
       'DP Conway ', 'DCS Compton ', 'DPMD Jayawardene ',
       'Inzamam-ul-Haq ', 'FMM Worrell ', 'CP Mead ', 'Abid Ali ',
       'MJ Clarke ', 'KC Bland ', 'B Mitchell ', 'Hon.FS Jackson ',
       'TT Samaraweera ', 'RN Harvey ', 'KD Walters ', 'SJ McCabe ',
       'DR Jardine '], dtype=object)

In [83]:
matches.dtypes

Player                  object
Matches_Played           int64
innings_batted           int64
not_outs                 int64
runs_scored              int64
highest_inns_score       int32
batting_average        float64
balls_faced              int32
batting_strike_rate      int32
100_scored               int64
50_scored                int64
ducks_scored             int64
boundary_fours           int64
boundary_sixes           int64
Rookie_Year              int32
Final_Year               int32
Country                 object
dtype: object

In [82]:
matches["batting_strike_rate"] = matches["batting_strike_rate"].astype(int)

In [84]:
matches['Career_length'] = matches['Final_Year']-matches['Rookie_Year']
matches

,Player,Matches_Played,innings_batted,not_outs,runs_scored,highest_inns_score,batting_average,balls_faced,batting_strike_rate,100_scored,50_scored,ducks_scored,boundary_fours,boundary_sixes,Rookie_Year,Final_Year,Country,Career_length
0,DG Bradman,52,80,10,6996,334,99.94,9800,58,29,13,7,626,6,1928,1948,AUS,20
1,HC Brook,12,20,1,1181,186,62.15,1287,91,4,7,1,141,23,2022,2023,ENG,1
2,AC Voges,20,31,7,1485,269,61.87,2667,55,5,4,2,186,5,2015,2016,AUS,1
3,RG Pollock,23,41,4,2256,274,60.97,1707,54,7,11,1,246,11,1963,1970,SA,7
4,GA Headley,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,1930,1954,WI,24
5,H Sutcliffe,54,84,9,4555,194,60.73,6558,34,16,23,2,202,6,1924,1935,ENG,11
6,E Paynter,20,31,5,1540,243,59.23,1288,45,4,7,3,125,4,1931,1939,ENG,8
7,KF Barrington,82,131,15,6806,256,58.67,4957,42,20,35,5,591,27,1955,1968,ENG,13
8,ED Weekes,48,81,5,4455,207,58.61,0,0,15,19,6,258,2,1948,1958,WI,10
9,SPD Smith,102,181,22,9320,239,58.61,17292,53,32,39,9,1026,52,2010,2023,AUS,13
10,WR Hammond,85,140,16,7249,336,58.45,7491,38,22,24,4,419,27,1927,1947,ENG,20
11,GS Sobers,93,160,21,8032,365,57.78,4063,53,26,30,12,593,32,1954,1974,WI,20
12,KC Sangakkara,134,233,17,12400,319,57.40,22882,54,38,52,11,1491,51,2000,2015,SL,15
13,DJ Mitchell,18,27,4,1316,190,57.21,2395,54,5,8,1,130,26,2019,2023,NZ,4
14,JB Hobbs,61,102,7,5410,211,56.94,5363,46,15,28,4,276,8,1908,1930,ENG,22
15,CL Walcott,44,74,7,3798,220,56.68,0,0,15,14,1,107,11,1948,1960,WI,12
16,L Hutton,79,138,15,6971,364,56.67,2844,39,19,33,5,358,7,1937,1955,ENG,18
17,JH Kallis,166,280,40,13289,224,55.37,28903,45,45,58,16,1488,97,1995,2013,ICC/SA,18
18,GE Tyldesley,14,20,2,990,122,55.00,178,29,3,6,2,37,2,1921,1929,ENG,8
19,KS Williamson,94,164,16,8124,251,54.89,15785,51,28,33,10,897,21,2010,2023,NZ,13
20,CA Davis,15,29,5,1301,183,54.20,665,35,4,4,1,65,1,1968,1973,WI,5
21,VG Kambli,17,21,1,1084,227,54.20,1823,59,4,3,3,124,6,1993,1995,IND,2
22,GS Chappell,87,151,19,7110,247,53.86,13079,51,24,31,12,755,16,1970,1984,AUS,14
23,AD Nourse,34,62,7,2960,231,53.81,108,63,9,14,3,115,6,1935,1951,SA,16
24,SR Tendulkar,200,329,33,15921,248,53.78,29437,54,51,68,14,2058,69,1989,2013,IND,24
25,M Labuschagne,43,76,5,3789,215,53.36,7146,53,11,16,4,427,12,2018,2023,AUS,5
26,BC Lara,131,232,6,11953,400,52.88,19753,60,34,48,17,1559,88,1990,2006,ICC/WI,16
27,Javed Miandad,124,189,21,8832,280,52.57,15164,45,23,43,6,788,48,1976,1993,PAK,17
28,R Dravid,164,286,32,13288,270,52.31,31258,42,36,63,8,1654,21,1996,2012,ICC/IND,16
29,Mohammad Yousuf,90,156,12,7530,223,52.29,14372,52,24,33,11,957,51,1998,2010,PAK,12
30,Younis Khan,118,213,19,10099,313,52.05,19375,52,34,33,19,1082,70,2000,2017,PAK,17
31,RT Ponting,168,287,29,13378,257,51.85,22782,58,41,62,17,1509,73,1995,2012,AUS,17
32,J Ryder,20,32,5,1394,201,51.62,2035,44,3,9,1,102,3,1920,1929,AUS,9
33,A Flower,63,112,19,4794,232,51.54,10636,45,12,27,5,543,20,1992,2002,ZIM,10
34,MEK Hussey,79,137,16,6235,195,51.52,12436,50,19,29,12,685,39,2005,2013,AUS,8
35,S Chanderpaul,164,280,49,11867,203,51.37,27395,43,30,66,15,1285,36,1994,2015,WI,21
36,SM Gavaskar,125,214,16,10122,236,51.12,14184,43,34,45,12,908,26,1971,1987,IND,16
37,SR Waugh,168,260,46,10927,200,51.06,22461,48,32,50,22,1175,20,1985,2004,AUS,19
38,Abdullah Shafique,14,26,2,1220,201,50.83,2764,44,4,4,2,119,18,2021,2023,PAK,2
39,ML Hayden,103,184,14,8625,380,50.73,14349,60,30,29,14,1049,82,1994,2009,AUS,15
40,AB de Villiers,114,191,18,8765,278,50.66,16077,54,22,46,8,1024,64,2004,2018,SA,14
41,AR Border,156,265,44,11174,205,50.56,27002,41,27,63,11,1161,28,1978,1994,AUS,16
42,JE Root,135,247,20,11416,254,50.29,20113,56,30,60,12,1247,43,2012,2023,ENG,11
43,IVA Richards,121,182,12,8540,291,50.23,9613,69,24,45,10,952,84,1974,1991,WI,17
44,DP Conway,16,29,1,1403,200,50.10,2719,51,4,8,2,177,6,2021,2023,NZ,2
45,DCS Compton,78,131,15,5807,278,50.06,2731,38,17,28,10,342,3,1937,1957,ENG,20
46,DPMD Jayawardene,149,252,15,11814,374,49.84,22959,51,34,50,15,1387,61,1997,2014,SL,17
47,Inzamam-ul-Haq,120,200,22,8830,329,49.60,16345,54,25,46,15,1105,48,1992,2007,ICC/PAK,15
48,FMM Worrell,51,87,9,3860,261,49.48,488,40,9,22,11,240,11,1948,1963,WI,15
49,CP Mead,17,26,2,1185,182,49.37,619,30,4,3,3,38,0,1911,1928,ENG,17
52,Abid Ali,16,26,2,1180,215,49.16,2445,48,4,3,2,148,5,2019,2021,PAK,2
53,MJ Clarke,115,198,22,8643,329,49.10,15456,55,28,27,9,978,39,2004,2015,AUS,11
54,KC Bland,21,39,5,1669,144,49.08,885,37,3,9,2,123,20,1961,1966,SA,5
55,B Mitchell,42,80,9,3471,189,48.88,158,29,8,21,3,41,1,1929,1949,SA,20
56,Hon.FS Jackson,20,33,4,1415,144,48.79,0,0,5,6,3,51,0,1893,1905,ENG,12
57,TT Samaraweera,81,132,20,5462,231,48.76,11641,46,14,30,11,633,7,2001,2013,SL,12
58,RN Harvey,79,137,10,6149,205,48.41,1799,43,21,24,7,427,1,1948,1963,AUS,15
59,KD Walters,74,125,14,5357,250,48.26,8662,49,15,33,4,525,23,1965,1981,AUS,16
62,SJ McCabe,39,62,5,2748,232,48.21,3217,60,6,13,4,241,5,1930,1938,AUS,8
63,DR Jardine,22,33,6,1296,127,48.00,2110,25,1,10,2,53,0,1928,1934,ENG,6

In [85]:
#calculation with the dataframe

In [86]:
#Q1: Cricketers in this dataframe the avrage career length
matches["Career_length"].mean()

12.833333333333334

In [90]:
#Q2: AVG batting strike rate for Crickers who played aver 10 years
matches[matches['Career_length'] > 10]["batting_strike_rate"]

0     58
4     56
5     34
7     42
9     53
10    38
11    53
12    54
14    46
15     0
16    39
17    45
19    51
22    51
23    63
24    54
26    60
27    45
28    42
29    52
30    52
31    58
35    43
36    43
37    48
39    60
40    54
41    41
42    56
43    69
45    38
46    51
47    54
48    40
49    30
53    55
55    29
56     0
57    46
58    43
59    49
Name: batting_strike_rate, dtype: int32

In [97]:
#Q3 find number of cricketers who played before 1960
matches[matches["Rookie_Year"]< 1960]["Player"].count()

22

In [99]:
#Q4: Max Highest Inns score by country
matches.groupby("Country")["innings_batted"].max()

Country
AUS        287
ENG        247
ICC/IND    286
ICC/PAK    200
ICC/SA     280
ICC/WI     232
IND        329
NZ         164
PAK        213
SA         191
SL         252
WI         280
ZIM        112
Name: innings_batted, dtype: int64

In [101]:
matches.groupby("Country")["innings_batted"].max().to_frame("Highinncountry").reset_index().sort_values("Highinncountry", ascending = False)

    Country  Highinncountry
6       IND             329
0       AUS             287
2   ICC/IND             286
4    ICC/SA             280
11       WI             280
10       SL             252
1       ENG             247
5    ICC/WI             232
8       PAK             213
3   ICC/PAK             200
9        SA             191
7        NZ             164
12      ZIM             112

In [106]:
#Q5: 5 Hundreds, fifties, ducks(0) avg by country
Q5 = matches.groupby("Country")["100_scored","50_scored","ducks_scored"].mean()

C:\Users\OrdiOne\AppData\Local\Temp\ipykernel_3956\1222529283.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  Q5 = matches.groupby("Country")["100_scored","50_scored","ducks_scored"].mean()

In [107]:
Q5

         100_scored  50_scored  ducks_scored
Country
AUS       21.533333  29.466667      9.000000
ENG       12.307692  20.769231      4.307692
ICC/IND   36.000000  63.000000      8.000000
ICC/PAK   25.000000  46.000000     15.000000
ICC/SA    45.000000  58.000000     16.000000
ICC/WI    34.000000  48.000000     17.000000
IND       29.666667  38.666667      9.666667
NZ        12.333333  16.333333      4.333333
PAK       17.800000  23.200000      8.000000
SA         9.800000  20.200000      3.400000
SL        28.666667  44.000000     12.333333
WI        16.625000  25.625000      7.250000
ZIM       12.000000  27.000000      5.000000

In [112]:
result = Q5.sort_values(by=["100_scored", "50_scored", "ducks_scored"], ascending=False)
result

         100_scored  50_scored  ducks_scored
Country
ICC/SA    45.000000  58.000000     16.000000
ICC/IND   36.000000  63.000000      8.000000
ICC/WI    34.000000  48.000000     17.000000
IND       29.666667  38.666667      9.666667
SL        28.666667  44.000000     12.333333
ICC/PAK   25.000000  46.000000     15.000000
AUS       21.533333  29.466667      9.000000
PAK       17.800000  23.200000      8.000000
WI        16.625000  25.625000      7.250000
NZ        12.333333  16.333333      4.333333
ENG       12.307692  20.769231      4.307692
ZIM       12.000000  27.000000      5.000000
SA         9.800000  20.200000      3.400000